# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2021-05-19T07:00:02Z"
  labels:
    name: train-task-003
  name: train-task-003
  namespace: default
  resourceVersion: "3648771"
  selfLink: /apis/batch/v1/namespaces/default/jobs/train-task-003
  uid: b1a026fe-4ba3-45ce-be0a-b4764e1ffdb4
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: b1a026fe-4ba3-45ce-be0a-b4764e1ffdb4
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: b1a026fe-4ba3-45ce-be0a-b4764e1ffdb4
        job-name: train-task-003
        name: train-task-003
      name: train-task-003-pod
    spec:
      containers:
      - args:
        - python /home/work/test.py
        command:
        - /bin/sh
        - -c
        env:
        - name: OCTPS_TRAIN_TASK_ID
          value: task-1
        image: registry-cbu.huawei.com/huawei-iasbu-octopus/test:0.0.1
        imagePullPolicy: IfNotPresent
        name: container-train-task-003
        resources:
          limits:
            cpu: "5"
            memory: 50Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "5"
            memory: 50Gi
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: dev/shm
          name: vol-train-task-003
      dnsPolicy: ClusterFirst
      nodeSelector:
          node: nvidia-v100
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: vol-train-task-003
